# Generated by Django 4.2.7 on 2024-10-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='id',
            new_name='region_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='id',
            new_name='service_id',
        ),
    ]
