# Generated by Django 4.2.7 on 2024-10-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0003_rename_region_id_region_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestationpriseencharge',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='etatapreciatif',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='ordreentree',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='ordresortie',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='pvrecensement',
            name='Region',
        ),
    ]
