# Generated by Django 5.1.2 on 2024-10-26 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0004_remove_attestationpriseencharge_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatapreciatif',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimoine.service'),
        ),
    ]
