# Generated by Django 5.1.2 on 2024-10-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0005_alter_etatapreciatif_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatapreciatif',
            name='Service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
