# Generated by Django 5.1.2 on 2024-10-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0007_remove_etatapreciatif_libelle_chapitre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatapreciatif',
            name='Inventaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='etats_apreciatifs', to='patrimoine.inventaire'),
            preserve_default=False,
        ),
    ]
