# Generated by Django 5.1.2 on 2024-10-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0008_etatapreciatif_inventaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatapreciatif',
            name='Inventaire',
        ),
    ]
